# Prompt set data, part 6: weapons and gear, working tools, carried loads, ceremony things, nature.
def P(id, en, km, size, budget, prompt, note=''):
    return dict(id=id, en=en, km=km, size=size, budget=budget, prompt=prompt, note=note)

WEAPONS = [
 P('weapon-preah-khan', 'Sword of state (Preah Khan)', 'ព្រះខ័នរាជ្យ', '0.9 m', '2k', 'The Khmer royal sword of state: a straight double-edged steel blade with a central ridge, a gold hilt with a tall pommel shaped like a stupa, a small cross-guard with curled ends, the grip wrapped in gold, a scabbard is not needed.', 'The sacred sword is still part of Cambodian royal regalia; Angkor-era form assumed.'),
 P('weapon-dao', 'Dao sword (soldier)', 'ដាវ', '0.8 m', '1k', 'A Khmer soldier\'s single-edged sword: a straight heavy blade widening slightly towards a squared tip, a long wooden grip bound with cord, no guard.'),
 P('weapon-dao-noble', 'Dao sword (commander)', 'ដាវមេទ័ព', '0.9 m', '2k', 'A Khmer commander\'s sword: a single-edged blade with a slight curve near the tip, a long grip wrapped in red cord, a gilded bronze pommel and small guard.'),
 P('weapon-spear', 'Spear', 'លំពែង', '2.2 m', '1k', 'A Khmer infantry spear: a long straight bamboo shaft, a leaf-shaped iron blade bound with cord, a small red tassel below the blade.'),
 P('weapon-javelin', 'Javelin', 'ស្នែង', '1.6 m', '600', 'A light throwing javelin: a thin bamboo shaft, a small barbed iron head.'),
 P('weapon-lance', 'Cavalry lance', 'លំពែងទ័ពសេះ', '2.8 m', '1k', 'A long cavalry lance: a straight hardwood shaft, a narrow iron blade, a short cloth pennant (team colour) below the blade.'),
 P('weapon-longbow', 'Longbow and arrow', 'ធ្នូ', '1.5 m', '1k', 'A Khmer longbow of bamboo with gently recurved tips and a cord string, and one arrow with a bamboo shaft, an iron head and feather fletching (two separate pieces side by side).'),
 P('weapon-hunting-bow', 'Hunting bow', 'ធ្នូព្រាន', '1.3 m', '1k', 'A short hunting bow of bamboo bound with rattan, a plant-fibre string.'),
 P('weapon-crossbow-ballista', 'Elephant crossbow (double bow)', 'ស្នាធ្នូដំរី', '2.5 m wide', '4k', 'A large two-bow crossbow mounted on a wooden frame as on the Bayon war elephants: two bows one behind the other, a long stock with a trigger, a heavy bolt.', 'Carved on the Bayon and Banteay Chhmar (HISTORICALLY_CONFIRMED).'),
 P('weapon-ankus', 'Elephant goad (ankus)', 'កង្វេរ', '0.7 m', '600', 'An elephant goad: a short wooden handle with a bronze head bearing a straight point and a curved hook.'),
 P('weapon-axe', 'Iron axe', 'ពូថៅ', '0.7 m', '600', 'A Khmer iron axe: a narrow iron head socketed onto a curved wooden handle.'),
 P('shield-round-kala', 'Round shield with monster face', 'ខែលមុខរាហូ', '0.7 m wide', '1k', 'A round shield of hide over a wicker frame, convex, painted with a fierce kala/monster face in red and black, a hand grip at the back.', 'Shields with monster faces appear on the Angkor Wat reliefs.'),
 P('shield-tall-rect', 'Tall rectangular shield', 'ខែលវែង', '1.2 m tall', '800', 'A tall rectangular infantry shield of wood and hide with a pointed top, painted with a plain area for the team colour and a border.'),
 P('gear-quiver', 'Quiver with arrows', 'បំពង់ព្រួញ', '0.8 m', '1k', 'A cylindrical quiver of woven rattan with a leather strap, a dozen fletched arrows sticking out.'),
 P('gear-howdah', 'Elephant howdah', 'កូប', '1.8 × 1.2 m', '4k', 'A Khmer war-elephant howdah: a wooden platform seat with a low carved railing on three sides, red cushions, two tall sockets for parasols at the back, ropes to tie it on.'),
 P('gear-parasol-rank', 'Rank parasol', 'ឆត្រ', '2.2 m', '2k', 'A Khmer ceremonial parasol: a long gilded pole, a flat round canopy of red silk with a gold fringe and a gold knob on top.', 'The Angkor Wat procession counts parasols to show rank (Suryavarman II has 15).'),
 P('gear-parasol-royal', 'Royal tiered parasol', 'ឆត្រព្រះមហាក្សត្រ', '3 m', '3k', 'A royal tiered parasol: three stacked white-and-gold canopies getting smaller upwards on a tall gilded pole, gold fringes.'),
 P('gear-banner-standard', 'Army standard', 'ទង់ទ័ព', '3.5 m', '2k', 'A Khmer army standard: a tall pole topped by a small carved gilded figure of Garuda, a long narrow cloth banner hanging below (team colour).'),
]

TOOLS = [
 P('tool-hoe', 'Hoe', 'ចប', '1.2 m', '500', 'A Khmer farming hoe: a broad iron blade set at a right angle on a wooden handle.'),
 P('tool-sickle', 'Harvest sickle', 'កណ្ដៀវ', '0.4 m', '500', 'A Cambodian rice sickle: a thin crescent iron blade with a serrated edge on a short wooden handle.'),
 P('tool-digging-stick', 'Digging stick', 'ដងជីក', '1.5 m', '300', 'A heavy wooden digging stick with a fire-hardened pointed end, an iron tip sleeve.'),
 P('tool-axe-adze', 'Axe-adze', 'ពូថៅកាប់', '0.7 m', '600', 'A Khmer axe-adze: an iron blade set crosswise on a bent wooden handle for shaping timber.'),
 P('tool-mallet', 'Wooden mallet', 'ញញួរឈើ', '0.5 m', '400', 'A heavy wooden mallet with a round head carved from one piece of hardwood.'),
 P('tool-chisels', 'Stone chisels set', 'ដែកឆ្លាក់', '0.3 m each', '600', 'Three iron stone-carving chisels of different widths and a pointed punch, laid side by side.'),
 P('tool-stone-hammer', 'Stone hammer', 'ញញួរថ្ម', '0.4 m', '400', 'A quarryman\'s hammer: a heavy iron head on a short thick wooden handle.'),
 P('tool-carrying-pole', 'Carrying pole with two baskets', 'ដងរែក', '1.8 m', '2k', 'A Cambodian carrying pole: a flexible bamboo pole with a woven basket hanging from each end on cords, both baskets full of rice.'),
 P('tool-tump-basket', 'Back basket with tump strap', 'កញ្ជើស្ពាយ', '0.6 m', '1k', 'A tall conical woven bamboo back-basket with a woven tump strap for the forehead.'),
 P('tool-cast-net', 'Cast net', 'សំណាញ់', '1 m folded', '1k', 'A gathered fishing cast net of fine cord with small lead sinkers round the edge, hanging in folds as held for throwing.'),
 P('tool-fish-creel', 'Fish creel', 'ឆ្នុក', '0.35 m', '600', 'A small Cambodian fish basket woven of bamboo with a narrow neck and a cord to tie it at the waist.'),
 P('tool-fish-trap', 'Fish trap', 'លប', '1 m', '1k', 'A cylindrical Cambodian fish trap of split bamboo with a funnel entrance.'),
 P('tool-goad-staff', 'Driver\'s staff', 'ដំបង', '1.5 m', '300', 'A smooth bamboo staff with a short iron point at one end.'),
 P('tool-cooking-pot', 'Earthenware cooking pot', 'ឆ្នាំងដី', '0.3 m', '600', 'A round-bottomed Khmer earthenware cooking pot, reddish-brown with black soot, on three hearth stones.'),
 P('tool-paddle-anvil', 'Potter\'s paddle and anvil', 'ក្ដារវាយឆ្នាំង', '0.3 m', '400', 'A Khmer potter\'s wooden paddle and a round fired-clay anvil stone, side by side.'),
 P('tool-backstrap-loom', 'Backstrap loom with cloth', 'កីត្បាញ', '1.5 m', '3k', 'A simple backstrap loom: warp threads tied to a post, wooden bars, a half-woven striped cotton cloth.', 'Angkorian loom types are undocumented (HISTORICALLY_UNCERTAIN).'),
 P('tool-forge', 'Village forge', 'ចង្ក្រានដែក', '1.5 m', '3k', 'A Khmer village forge: a small clay furnace, two vertical bamboo piston bellows, an iron anvil on a log, tongs and a hammer.'),
 P('tool-gold-pan', 'Gold pan', 'ចានលាងមាស', '0.5 m', '400', 'A shallow wooden gold-washing pan with a little gravel and gold specks.'),
 P('tool-offering-tray', 'Offering tray with lamp', 'ថាសតង្វាយ', '0.4 m', '800', 'A round bronze offering tray with a pedestal, jasmine flowers, a small oil lamp and incense.'),
 P('tool-conch', 'Ritual conch', 'ស័ង្ខ', '0.3 m', '600', 'A white ritual conch shell mounted on a small gilded stand.'),
 P('tool-palm-manuscript', 'Palm-leaf manuscript', 'សាស្ត្រាស្លឹករឹត', '0.5 m', '400', 'A bundle of long narrow palm-leaf pages with incised script, threaded on a cord between two lacquered wooden covers.'),
 P('tool-stylus', 'Iron stylus', 'ដែកចារ', '0.2 m', '200', 'A thin iron stylus with a pointed tip for writing on palm leaf.'),
 P('tool-fan', 'Palm fan', 'ផ្លិត', '0.6 m', '400', 'A large court fan of palm leaf on a gilded handle.'),
 P('tool-fly-whisk', 'Fly-whisk', 'ផ្ដិតរុយ', '0.6 m', '400', 'A royal fly-whisk of white yak hair on a gold handle.'),
 P('tool-war-drum', 'War drum', 'ស្គរយុទ្ធ', '0.8 m', '1k', 'A Khmer war drum: a barrel of wood with hide heads laced together, hanging from a carrying pole.'),
 P('tool-gong', 'Gong', 'គង', '0.6 m', '1k', 'A bronze gong with a raised central boss hanging from a wooden frame, a padded beater.'),
 P('tool-medicine-jars', 'Medicine jars', 'ពាងថ្នាំ', '0.3 m', '600', 'Three small Khmer glazed stoneware jars with lids, brown and green glaze, on a tray.'),
 P('tool-walking-stick', 'Walking stick', 'ឈើច្រត់', '1.2 m', '200', 'A twisted hardwood walking stick.'),
 P('tool-toy-buffalo', 'Child\'s toy', 'តុក្កតា', '0.15 m', '400', 'A small clay toy water buffalo on wheels.'),
 P('tool-balance-scale', 'Balance scale', 'ជញ្ជីង', '0.5 m', '600', 'A small bronze hanging balance scale with two pans on cords.'),
 P('tool-rice-mortar', 'Rice mortar and pestle', 'ត្បាល់កិន', '1 m', '1k', 'A deep wooden rice mortar carved from a log and a long heavy wooden pestle.'),
 P('prop-storage-jar', 'Khmer storage jar', 'ពាង', '0.8 m', '800', 'A large Khmer stoneware storage jar with a brown-black glaze, a wide shoulder and small lug handles.'),
 P('prop-celadon', 'Chinese celadon ware', 'ចានចិន', '0.3 m', '800', 'A Song-dynasty Chinese celadon bowl and a small jar with a pale blue-green glaze.'),
 P('prop-trade-bale', 'Trade bale', 'កញ្ចប់ទំនិញ', '0.8 m', '400', 'A bale of goods wrapped in woven matting and tied with rattan.'),
 P('prop-hearth', 'Three-stone hearth', 'ចង្ក្រានថ្ម', '0.6 m', '400', 'A cooking hearth of three stones with ashes and a few burning sticks.'),
 P('prop-sacred-fire-ark', 'Sacred fire ark', 'ហិបភ្លើងពិសិដ្ឋ', '1.5 m', '2k', 'The sacred fire carried in the royal procession: a small gilded ark with a pointed roof and a flame inside, on two carrying poles.', 'Carried by Brahmins in the Angkor Wat procession (HISTORICALLY_CONFIRMED).'),
]

LOADS = [
 P('load-rice-basket', 'Rice sheaves in a head basket', 'កញ្ជើស្រូវ', '0.6 m', '1k', 'A round woven basket full of golden rice sheaves, the kind carried on the head on a cloth pad.'),
 P('load-log-bundle', 'Bundle of logs', 'ចំណងឈើ', '1.6 m', '600', 'Three thick debarked logs tied together with rattan, carried on the shoulder.'),
 P('load-stone-block', 'Sandstone block on a head pad', 'ដុំថ្មលើក្បាល', '0.5 m', '300', 'A small dressed sandstone block resting on a round twisted cloth head pad.'),
 P('load-gold-basket', 'Lidded basket for gold and gems', 'កញ្ជើមាស', '0.3 m', '500', 'A small tightly woven lidded basket with a few gold nuggets, blue sapphires and red rubies spilling out.'),
]

NATURE = [
 P('plant-banyan', 'Banyan tree', 'ដើមជ្រៃ', '18 m tall, 20 m crown', '10k', 'A great banyan tree (Ficus): a massive trunk of many twisting stems with buttress roots, a curtain of hanging aerial roots, broad branches under a wide layered crown of dark green leaves.'),
 P('plant-sugar-palm', 'Sugar palm (thnot)', 'ដើមត្នោត', '15 m', '3k', 'A Cambodian sugar palm (Borassus flabellifer): a tall straight grey trunk ringed with leaf scars, a round crown of stiff fan-shaped leaves at the top, clusters of dark round fruit.'),
 P('plant-bamboo', 'Bamboo clump', 'គុម្ពឫស្សី', '10 m', '4k', 'A dense clump of giant thorny bamboo: tall green culms arching outwards, feathery leaves.'),
 P('plant-mango', 'Mango tree', 'ដើមស្វាយ', '10 m', '5k', 'A mango tree: a short thick trunk, a dense dome of dark glossy leaves, hanging green-yellow mangoes.'),
 P('plant-tamarind', 'Tamarind tree', 'ដើមអម្ពិល', '12 m', '5k', 'A tamarind tree: a rough dark trunk, a broad spreading crown of fine feathery leaves, brown curved pods.'),
 P('plant-dipterocarp', 'Forest tree (chheuteal)', 'ដើមឈើទាល', '30 m', '5k', 'A tall Dipterocarpus alatus forest tree: a straight pale grey trunk without branches for most of its height, a small high rounded crown.'),
 P('plant-strangler-fig', 'Strangler fig on a ruin wall', 'ដើមស្ពង់', '12 m', '8k', 'A spung tree (Tetrameles nudiflora) with huge pale roots pouring over a fallen sandstone wall, as at Ta Prohm today (for ruin scenes only).', 'Grew after abandonment: not for temples shown when new.'),
 P('plant-lotus-pond', 'Lotus patch', 'ឈូក', '2 × 2 m', '2k', 'A patch of sacred lotus on still water: round green leaves standing above the water, pink flowers and seed pods.'),
 P('plant-banana', 'Banana plant', 'ដើមចេក', '4 m', '2k', 'A banana plant with large torn green leaves and a hanging bunch of green bananas and a purple flower.'),
 P('plant-grass-clump', 'Grass clump', 'គុម្ពស្មៅ', '0.6 m', '300', 'A clump of tall tropical grass blades.'),
 P('res-stone-outcrop', 'Sandstone outcrop (quarry)', 'ផ្ទាំងថ្មភក់', '8 m', '3k', 'A low outcrop of grey-yellow Kulen sandstone with flat bedding layers, a few rectangular blocks partly cut out with wedge marks.'),
 P('res-laterite-pit', 'Laterite pit', 'អណ្ដូងបាយក្រៀម', '6 m', '2k', 'A shallow quarry pit in red laterite ground with block-shaped cuts in its walls.'),
 P('res-gold-vein', 'Gold-bearing rock', 'ថ្មមានមាស', '4 m', '2k', 'A pale quartz rock outcrop with glints of gold in its cracks beside river gravel.'),
 P('res-fruit-tree', 'Wild fruit grove', 'ចំការផ្លែឈើ', '6 m', '4k', 'Two small wild fruit trees heavy with yellow and red fruit, fallen fruit underneath.'),
 P('res-gem-gravel', 'Gem gravel (Pailin)', 'ដីត្បូង', '4 m', '1k', 'A patch of dark red gravel with a few rough blue sapphires and red rubies showing.', 'Pailin gem mining is recorded from the 19th century; earlier use is a game rule.'),
]
