# Prompt set data, part 1: heroes, kings, army units, enemies.
# Each item: id (= file name without .glb), en, km, size (real), budget (triangles after shrink),
# prompt (the subject; the kind's standard framing is appended), note (evidence / tips).

HEROES = [
 dict(id='hero-king', en='The King (hero, PK concept sheet)', km='ព្រះមហាក្សត្រ', size='1.70 m tall (body), crown adds ~0.45 m', budget='24k',
  prompt='A Khmer king of the Angkor era, about 35 years old, strong athletic build, warm brown skin, calm proud face with almond eyes, full lips and a small moustache, long earlobes stretched by heavy gold ear pendants. He wears a tall conical gold mokot crown in tiered rings ending in a slender spire, with a jewelled diadem band over the forehead and leaf-shaped side flaps over the ears. A gold cuirass covers chest and belly, finely engraved with lotus scrolls, its upper edge a scalloped collar, a red gem where two crossing straps meet at the chest. Gold armlets on both upper arms, broad gold bracelets, gold anklets. A royal sampot of dense purple silk with a gold lozenge pattern and red-and-green hem stripes, wrapped and drawn up between the legs (chong kben) to just above the knee, a long pointed gold-edged front panel hanging between the thighs, a broad gold medallion belt with hanging gold hip flaps. Barefoot.',
  note='Matches PK\'s concept sheet (game choice: the cuirass). Zhou Daguan (1296) describes the king\'s gold crown or jasmine wreath, pearls, gold bracelets and anklets, bare feet. The sword of state is a separate file (weapon-preah-khan).'),
 dict(id='hero-worker', en='Worker hero (axe)', km='អ្នកស្រុកក្លាហាន', size='1.62 m', budget='16k',
  prompt='A young Khmer village man of the Angkor era, lean and muscular from hard labour, sun-darkened brown skin, short black hair tied in a small top-knot, a plain cotton cloth band round the forehead. Bare chest. A short undyed brown cotton sampot wrapped round the hips and drawn up between the legs (chong kben) to mid-thigh, tucked at the waist, a red-and-white checked krama scarf tied round the waist as a belt with the ends hanging at the hip. A small woven rattan pouch on a cord at the hip. Bare feet with dusty soles, calloused hands.',
  note='Commoners: bare chest, plain sampot, top-knot (Bayon daily-life reliefs). The krama check pattern is later tradition (used as the game\'s team colour). Axe = weapon-axe.'),
 dict(id='hero-spear', en='Spearman hero', km='ពលលំពែងក្លាហាន', size='1.65 m', budget='16k',
  prompt='A Khmer foot soldier of King Suryavarman II\'s army (12th century, Angkor Wat reliefs), fit and broad-shouldered, brown skin, fierce focused face. He wears a helmet topped by a carved animal crest (a stylised deer or bird head) over a hair bun, a short protective cuirass of hardened leather plates laced together over chest and back, plain shoulders. A dark red sampot drawn up between the legs (chong kben) to mid-thigh, a cloth belt. Simple bronze armlets. Bare legs and feet.',
  note='Angkor Wat south gallery: troops of named commanders, many with animal-crest helmets and body protection. Spear and shield are separate files (weapon-spear, shield-round-kala).'),
 dict(id='hero-sword', en='Swordsman hero (elite guard)', km='ពលដាវក្លាហាន', size='1.68 m', budget='16k',
  prompt='An elite Khmer royal guard of the Angkor Wat era, tall and muscular, brown skin, short beard, intense eyes. Hair in a high bun wrapped with a red cloth. A cuirass of small overlapping bronze-coloured scales over the torso, a wide studded belt. A deep blue sampot drawn up between the legs (chong kben) above the knee with a short hanging front panel. Gold earrings, bronze armlets and wrist guards of wrapped cord. Bare legs and feet with cord anklets.',
  note='Scale cuirasses appear on the Bayon reliefs; sword-and-shield fighters on both Angkor Wat and the Bayon. Sword = weapon-dao, shield = shield-round-kala.'),
 dict(id='hero-bow', en='Archer hero', km='ពលធ្នូក្លាហាន', size='1.64 m', budget='16k',
  prompt='A Khmer archer of the Angkor era, wiry and alert, brown skin, narrow keen eyes, hair in a top-knot tied with a strip of cloth. Bare chest crossed by a leather strap that holds a quiver on the back (quiver shown empty and flat against the back). A green-grey sampot drawn up between the legs (chong kben) to mid-thigh, a leather bracer on the left forearm, a cord belt with a small knife sheath. Bare feet.',
  note='Bowmen appear on the Angkor Wat and Bayon reliefs. Bow and arrows = weapon-longbow; quiver = gear-quiver.'),
 dict(id='hero-rider', en='Cavalry rider hero', km='ទ័ពសេះក្លាហាន', size='1.65 m (rider only)', budget='16k',
  prompt='A Khmer cavalryman of the 12th century, compact strong build, brown skin, hair in a bun under a small peaked cloth cap tied under the chin. Bare chest with a cross-belt, a short padded cotton tunic-vest without sleeves, a dark orange sampot drawn up between the legs (chong kben) above the knee, legs bare for riding, cord anklets. Sitting legs: generate him standing in the A-pose (the game seats him on the horse).',
  note='Horsemen ride without stirrups on the Angkor Wat reliefs. The horse is a separate file (animal-horse-war). Lance = weapon-lance.'),
 dict(id='hero-elephant', en='Mahout hero (war elephant driver)', km='គ្រូដំរីក្លាហាន', size='1.60 m (mahout only)', budget='16k',
  prompt='A Khmer mahout (elephant driver) of the Angkor era, lean and agile, dark brown skin, weathered face, hair in a top-knot with a white cloth band. Bare chest with a cord of protective amulets (small metal cylinders) across the body. A short dark sampot drawn up between the legs (chong kben), high on the thigh for riding, a cloth belt with a small pouch. Bare legs and feet, toes spread. Generate standing in the A-pose (the game seats him on the elephant\'s neck).',
  note='Mahouts sit on the neck with a goad (ankus) on the Angkor Wat and Bayon reliefs. Elephant = animal-elephant-war, howdah = gear-howdah, goad = weapon-ankus.'),
 dict(id='hero-commander', en='Army commander hero', km='មេទ័ពក្លាហាន', size='1.70 m', budget='20k',
  prompt='A Khmer army general of the Angkor Wat era, a powerful middle-aged noble, brown skin, a trimmed moustache and short beard, commanding face. A tall helmet shaped like a tiered conical crown with a crest of a mythical bird at the front. A cuirass of gilded bronze scales, a broad gold collar with pendant points, gold armlets and bracelets, heavy gold earrings. A rich red silk sampot with a gold pattern drawn up between the legs (chong kben) to the knee, a long front panel, a jewelled belt. Bare feet with gold anklets.',
  note='Named generals stand on elephants under parasols in the Angkor Wat procession. Sword = weapon-dao-noble; parasol = gear-parasol-rank.'),
 dict(id='hero-hunter', en='Hunter / watchman hero', km='ព្រានក្លាហាន', size='1.62 m', budget='16k',
  prompt='A Khmer forest hunter and scout of the Angkor era, lean and sinewy, very dark sun-tanned skin, sharp watchful eyes, hair tied in a rough top-knot with a leaf-green headband. Bare chest with a cord necklace of a boar tusk. A short faded brown sampot drawn up tight between the legs, a woven rattan belt with a small water gourd and a pouch, a blowing horn (small buffalo horn) hanging at the hip on a cord. Bare feet with scratched shins.',
  note='Scouts are a game abstraction; hunting scenes appear on the reliefs. Dog = animal-dog-village; bow = weapon-hunting-bow.'),
 dict(id='hero-cart', en='Ox-cart driver hero', km='អ្នករទេះគោក្លាហាន', size='1.60 m', budget='16k',
  prompt='A Khmer ox-cart driver of the Angkor era, an older stocky man with greying hair in a top-knot, kind weathered brown face, deep smile lines. Bare chest, a checked krama scarf over one shoulder, a plain brown sampot drawn up between the legs (chong kben) to the knee, a cloth belt with a betel pouch. Bare feet.',
  note='Ox-carts with arched roofs follow the army on the Bayon reliefs. Cart = vehicle-ox-cart; staff = tool-goad-staff.'),
]

KINGS = [
 dict(id='king-indravarman', en='King Indravarman I (Roluos, 877–889)', km='ព្រះបាទឥន្ទ្រវរ្ម័នទី១', size='1.70 m', budget='24k',
  prompt='A Khmer king of the late 9th century in the Preah Ko style, broad strong body, brown skin, serene face with a faint smile, a thin moustache. A cylindrical jewelled diadem with a low conical cover (mukuta) over a high chignon, small floral points round the band. Heavy gold ear pendants, a broad jewelled collar, armlets and bracelets. A pleated sampot of fine cotton falling to the knee with a pocket-like fold at the hip and a fishtail pleat at the front (Preah Ko statue style), a belt with a jewelled clasp. Bare chest, bare feet with anklets.',
  note='Dress after the Preah Ko and Bakong statues (Roluos style). No portrait of the king survives; this is the dress of his era.'),
 dict(id='king-suryavarman2', en='King Suryavarman II (builder of Angkor Wat, 1113–1150)', km='ព្រះបាទសូរ្យវរ្ម័នទី២', size='1.70 m', budget='24k',
  prompt='A Khmer emperor of the early 12th century as carved in the Angkor Wat audience scene, solid regal body, brown skin, calm commanding face. A tall conical tiered gold crown (mukuta) with a pointed finial and a diadem with triangular points, ornate ear pendants reaching the shoulders. A wide gold collar of hanging pendants, armlets, bracelets and anklets. A short silk sampot with a tight floral pattern, a long decorated front panel and flared side folds at the hips (Angkor Wat style), a jewelled belt with hanging pendants. Bare chest, bare feet.',
  note='Angkor Wat south gallery: Suryavarman II in audience and on his elephant under fifteen parasols (HISTORICALLY_CONFIRMED).'),
 dict(id='king-jayavarman7', en='King Jayavarman VII (Bayon, 1181–c.1218)', km='ព្រះបាទជ័យវរ្ម័នទី៧', size='1.70 m', budget='24k',
  prompt='A Khmer king of the late 12th century after his portrait statues: a full, heavy-set body, brown skin, a gentle meditative face with lowered eyes and a soft smile, long earlobes. Hair gathered in a small round bun on top of the head, no crown. Simple gold ear ornaments, a plain gold armlet on each arm. A short plain sampot with fine pleats and a narrow belt. Bare chest, bare feet. A quiet, compassionate Buddhist ruler.',
  note='The Jayavarman VII portrait heads (Preah Khan of Kompong Svay, Krol Romeas) show him without a crown, eyes half closed (HISTORICALLY_CONFIRMED). In procession he wears royal jewellery.'),
]

def era_soldier(id, en, km, prompt, note, budget='8k'):
    return dict(id=id, en=en, km=km, size='1.62 m', budget=budget, prompt=prompt, note=note)

UNITS = [
 dict(id='unit-villager-man', en='Villager (man)', km='អ្នកស្រុក', size='1.62 m', budget='6k',
  prompt='An ordinary Khmer village man of the Angkor era, slim and strong, brown skin, short black hair in a top-knot. Bare chest. A plain undyed cotton sampot wrapped at the hips and drawn up between the legs (chong kben) to mid-thigh, a narrow cloth belt with a krama scarf in the team colour (plain area for recolouring). Barefoot.',
  note='The game recolours the krama (team colour). Bayon daily-life reliefs.'),
 dict(id='unit-villager-woman', en='Villager (woman)', km='ស្ត្រីអ្នកស្រុក', size='1.52 m', budget='6k',
  prompt='An ordinary Khmer village woman of the Angkor era, slim, brown skin, long black hair gathered in a low bun with a small flower. A narrow cotton cloth wrapped over the chest (game modesty choice) and a long plain cotton sampot wrapped at the hips falling to mid-calf, folded at the front. Simple copper bracelets, barefoot.',
  note='Zhou Daguan and the reliefs show women bare-chested; the breast cloth is a game choice for a family audience (GAMEPLAY_ABSTRACTION).'),
 era_soldier('unit-spearman-early','Spearman, early eras (879–1060)','ពលលំពែង (សម័យដើម)',
  'A Khmer foot soldier of the 9th–11th century, lean, brown skin, hair in a top-knot. Bare chest with a cloth band crossing it. A short plain sampot drawn up between the legs (chong kben), a cloth belt in the team colour. Bare legs and feet. No armour.',
  'HISTORICALLY_UNCERTAIN: almost no battle scenes survive before Angkor Wat; simpler dress is extrapolated.'),
 era_soldier('unit-spearman-angkorwat','Spearman, Angkor Wat era (1113–1180)','ពលលំពែង (សម័យអង្គរវត្ត)',
  'A Khmer foot soldier of the Angkor Wat army: a helmet with a carved animal crest (deer, bird or horse head), a laced cuirass of hardened leather plates over chest and back, a dark sampot drawn up between the legs (chong kben), a cloth belt in the team colour. Bare legs and feet.',
  'Angkor Wat south gallery (HISTORICALLY_SUPPORTED).'),
 era_soldier('unit-spearman-bayon','Spearman, Bayon era (1181–1220)','ពលលំពែង (សម័យបាយ័ន)',
  'A Khmer foot soldier of Jayavarman VII\'s army: short cropped hair (no top-knot), a bare head, earlobes stretched, a cuirass of small scales or quilted cotton tied at the sides, a short sampot drawn up between the legs, a cloth belt in the team colour. Bare legs and feet.',
  'Bayon outer gallery: Khmer troops with short hair marching against Champa (HISTORICALLY_CONFIRMED).'),
 era_soldier('unit-swordsman-early','Swordsman, early eras','ពលដាវ (សម័យដើម)',
  'A Khmer warrior of the 9th–11th century, muscular, brown skin, hair in a high bun, bare chest with a cross-band, a short sampot drawn up between the legs, a cloth belt in the team colour, armlets of cord. Barefoot.',
  'HISTORICALLY_UNCERTAIN extrapolation.'),
 era_soldier('unit-swordsman-angkorwat','Swordsman, Angkor Wat era','ពលដាវ (សម័យអង្គរវត្ត)',
  'A Khmer elite swordsman of the Angkor Wat era: an animal-crest helmet, a cuirass of small scales, a sampot drawn up between the legs with a short front panel, wrist guards of cord, a belt in the team colour. Barefoot.',
  'Angkor Wat reliefs.'),
 era_soldier('unit-swordsman-bayon','Swordsman, Bayon era','ពលដាវ (សម័យបាយ័ន)',
  'A Khmer swordsman of the Bayon era: short cropped hair, bare head, a quilted cotton cuirass tied at the sides, a short sampot drawn up between the legs, a belt in the team colour. Barefoot.',
  'Bayon reliefs.'),
 era_soldier('unit-archer-early','Archer, early to Angkor Wat eras','ពលធ្នូ',
  'A Khmer bowman of the 9th–12th century, wiry, brown skin, top-knot, bare chest with a quiver strap across it (quiver on the back), a short sampot drawn up between the legs, a belt in the team colour. Barefoot.',
  'Bowmen on the Angkor Wat reliefs.'),
 era_soldier('unit-archer-bayon','Archer, Bayon era','ពលធ្នូ (សម័យបាយ័ន)',
  'A Khmer bowman of Jayavarman VII\'s army: short cropped hair, a quilted cotton vest, a quiver strap across the chest, a short sampot drawn up between the legs, a belt in the team colour. Barefoot.',
  'Bayon reliefs.'),
 era_soldier('unit-commander-angkorwat','Commander, Angkor Wat era','មេទ័ព (សម័យអង្គរវត្ត)',
  'A Khmer general of the Angkor Wat era: a tall tiered crown-helmet with a mythical-bird crest, a gilded scale cuirass, a broad gold collar, gold armlets and earrings, a rich silk sampot drawn up between the legs with a long front panel, gold anklets.',
  'Angkor Wat procession of generals.', budget='12k'),
 era_soldier('unit-commander-bayon','Commander, Bayon era','មេទ័ព (សម័យបាយ័ន)',
  'A Khmer general of the Bayon era: hair in a bun with a small jewelled diadem, a scale cuirass, a gold collar, armlets and earrings, a silk sampot drawn up between the legs with a long front panel.',
  'Bayon reliefs (officers on elephants).', budget='12k'),
 era_soldier('unit-watchman','Watchman / scout','អ្នកយាម',
  'A Khmer scout of the Angkor era, lean, dark sun-tanned skin, top-knot with a headband, bare chest, a short sampot drawn up between the legs, a woven belt with a gourd and a small buffalo horn trumpet at the hip. Barefoot.',
  'Game abstraction (scouts are not carved).'),
 era_soldier('unit-horseman','Horseman (rider only)','ទ័ពសេះ',
  'A Khmer cavalryman of the 12th century: hair in a bun under a small peaked cloth cap, a sleeveless padded cotton vest, a sampot drawn up between the legs above the knee, a belt in the team colour. Barefoot. Standing A-pose (seated on the horse in game).',
  'Angkor Wat reliefs show riders without stirrups.'),
 era_soldier('unit-buffalo-rider','Buffalo rider (rider only)','ទ័ពក្របី',
  'A Khmer village warrior who rides a water buffalo: stocky, brown skin, top-knot, bare chest, a short sampot drawn up between the legs, a belt in the team colour, a small round cloth cap. Barefoot. Standing A-pose.',
  'Buffalo riders are a game unit (GAMEPLAY_ABSTRACTION); buffaloes appear on the Bayon reliefs.'),
 era_soldier('unit-mahout','War elephant mahout (rider only)','គ្រូដំរី',
  'A Khmer mahout of the Angkor era: lean, bare chest with an amulet cord, a short sampot drawn up between the legs, a cloth band round the head. Barefoot. Standing A-pose (seated on the elephant in game).',
  'Angkor Wat and Bayon reliefs.'),
 era_soldier('unit-oxcart-driver','Ox-cart driver (rider only)','អ្នករទេះគោ',
  'A Khmer ox-cart driver: an older man, top-knot, bare chest, a krama over one shoulder, a sampot drawn up between the legs. Barefoot. Standing A-pose.',
  'Bayon reliefs (supply carts).'),
]

ENEMIES = [
 dict(id='enemy-cham-soldier', en='Cham soldier (Champa)', km='ទាហានចាម្ប៉ា', size='1.62 m', budget='8k',
  prompt='A soldier of the Champa kingdom (12th century) as carved on the Bayon: a distinctive headdress shaped like an upturned flower or lotus with petal-like flaps, a short-sleeved or sleeveless tunic tied at the waist, a short wrapped skirt over the hips, a belt in the team colour, a cord crossing the chest. Brown skin, a moustache, earrings. Barefoot.',
  note='Bayon and Banteay Chhmar reliefs: the Cham are told apart by their flower-like headdress (HISTORICALLY_CONFIRMED).'),
 dict(id='enemy-daiviet-soldier', en='Đại Việt soldier (Lý dynasty)', km='ទាហានដាយវៀត', size='1.62 m', budget='8k',
  prompt='A Vietnamese soldier of the Lý dynasty (11th–12th century): a dark brown knee-length tunic with a crossed collar and narrow sleeves, wide trousers tied at the calf, a cloth belt in the team colour, a small round helmet or a dark wrapped turban, black hair in a bun, bare feet or straw sandals.',
  note='HISTORICALLY_UNCERTAIN: Đại Việt troops are not carved at Angkor; dress follows later Vietnamese records and is an assumption.'),
 dict(id='enemy-rival-warrior', en='Rival chiefdom warrior', km='អ្នកចម្បាំងមេកន្ទ្រាញ', size='1.60 m', budget='8k',
  prompt='A warrior of a rival local chiefdom in 9th-century Cambodia: lean, brown skin, long hair tied loosely, a bark-cloth or plain cotton loincloth, a cord belt with team-coloured tassels, painted white stripes on the arms, bare chest and feet.',
  note='GAMEPLAY_ABSTRACTION: rival lords are named in inscriptions but never shown.'),
 dict(id='enemy-claimant-noble', en='Rival claimant noble', km='អ្នកដណ្ដើមរាជ្យ', size='1.68 m', budget='12k',
  prompt='A Khmer noble who claims the throne (9th–10th century): hair in a high bun with a small jewelled diadem, gold earrings and a collar, a silk sampot drawn up between the legs with a front panel, a belt in the team colour, bare chest and feet, a proud scornful face.',
  note='Succession wars are recorded in the inscriptions (e.g. after Yasovarman I).'),
]
