# Prompt set data, part 4: buildings, roads and water, ships and vehicles.
def B(id, en, km, size, budget, prompt, note=''):
    return dict(id=id, en=en, km=km, size=size, budget=budget, prompt=prompt, note=note)

BUILDINGS = [
 B('bld-royal-hall', 'Royal hall (town centre)', 'វាំងឈើ', '10 × 10 m footprint, 9 m high', '20k',
   'A Khmer royal audience hall of the Angkor era: a raised terrace of red laterite blocks faced with carved sandstone mouldings, 1.5 m high, with a broad front stair flanked by small stone lions. On it a wooden hall on dark hardwood posts with plank walls, carved wooden window shutters and a carved double door. A steep stacked roof of three overlapping tiers covered in dark grey-green glazed clay tiles, carved wooden gable boards with a sun motif, and curling naga-tail finials (chovea) at every ridge end and eave corner, gilded. A carved wooden balustrade round the terrace edge.',
   'Zhou Daguan: the palace was wood on a laterite terrace with lead and glazed tiles. Exact form lost; reconstruction from later Khmer wooden architecture.'),
 B('bld-house-commoner', 'Village house (commoner)', 'ផ្ទះរោង', '4 × 4 m, 5 m high', '6k',
   'A Khmer commoner\'s stilt house of the Angkor era: one room raised 2 m on round hardwood posts set on flat stones, walls of woven bamboo matting and split-bamboo panels in a wooden frame, a steep two-slope roof thatched thickly with dried palm leaves and grass, the thatch ridge bound with split bamboo, a simple wooden ladder to the door, a woven mat hanging as a door curtain. Under the house: a few clay water jars and a loom frame.',
   'Zhou Daguan: commoners\' roofs were thatch; only temples, the palace and nobles used tiles (HISTORICALLY_CONFIRMED). The game\'s current tiled houses are later tradition.'),
 B('bld-house-noble', 'Noble house', 'ផ្ទះកឹង', '6 × 6 m, 7 m high', '10k',
   'A Khmer noble\'s house of the 12th century: a large wooden house raised on tall carved hardwood posts on stone footings, dark vertical plank walls, shuttered windows, a steep two-tier roof of orange-red clay tiles with white lime-plastered ridge lines and upturned horn-shaped finials (kbach) at the ridge ends, a broad wooden stair with a carved handrail, a small veranda.',
   'Zhou Daguan: the houses of officials could have tiles on the main room only (HISTORICALLY_SUPPORTED).'),
 B('bld-storehouse', 'Storehouse / granary', 'ឃ្លាំង', '6 × 6 m, 5 m high', '8k',
   'A Khmer rice granary of the Angkor era: a square wooden storehouse raised 1.5 m on thick posts with wide wooden rat-guard discs on top of each post, plank walls, a single narrow door reached by a removable log ladder, a steep thatched roof; outside, a few large woven rice baskets and clay jars on a mat.',
   'Granaries are a later-tradition reconstruction (HISTORICALLY_SUPPORTED by need, form uncertain).'),
 B('bld-lumber-camp', 'Lumber camp', 'ឃ្លាំងឈើ', '6 × 6 m', '8k',
   'A Khmer woodcutters\' camp at the forest edge: an open shelter of four posts with a thatched lean-to roof, a stack of debarked hardwood logs held by stakes, a squared timber on two trestles with wood chips around it, an axe-adze stuck in a stump, a coil of rattan rope, a small cooking fire of three stones.',
   'Iron axes and adzes are attested; saws are not (no sawn planks: split and adzed).'),
 B('bld-barracks', 'War camp (barracks)', 'ជំរំទាហាន', '8 × 8 m', '12k',
   'A Khmer army camp of the 12th century: a long open hall on posts with a thatched roof, a low palisade of sharpened bamboo round it, a wooden rack of spears and round shields, a tall bamboo standard pole with a cloth banner (plain area for team colour), a hide-covered war drum on a frame, sleeping mats, a cooking area with clay pots.',
   'Army camps with cooking and standards are carved on the Bayon outer gallery.'),
 B('bld-market', 'Market', 'ផ្សារ', '8 × 8 m', '10k',
   'A Khmer market of the 13th century as Zhou Daguan saw it: no permanent building, an open trampled ground with woven palm mats laid out in rows, low bamboo frames with small palm-leaf shades over some mats, goods on the mats: baskets of rice, dried fish, fresh fish in shallow baskets, bananas and mangoes, Chinese blue-green celadon bowls and jars, rolls of cloth, a balance scale on a cloth, betel leaves and areca nuts.',
   'Zhou Daguan: women traded on mats on the ground, paying a fee for the place (HISTORICALLY_CONFIRMED).'),
 B('bld-river-landing', 'River landing (port)', 'កំពង់ផែ', '8 × 8 m, stage runs 6 m over water', '10k',
   'A Khmer river landing of the 12th century: a plank landing stage on rows of wooden posts running out over the water, wooden mooring posts, a storage shed with a thatched roof at the back on posts, large brown glazed Khmer storage jars, bales of goods wrapped in matting, a bamboo ladder down to the water.',
   'Reconstruction; river trade and Chinese ships are recorded by Zhou Daguan.'),
 B('bld-build-site', 'Temple building site', 'ការដ្ឋានសាងប្រាសាទ', '15 × 11 m', '16k',
   'A Khmer temple under construction (12th century): a half-built sandstone platform with blocks stacked unfinished and uncarved, an earth ramp up one side, a scaffold of bamboo lashed with rattan, a tall wooden shear-legs hoist with ropes and a pulley holding a large stone block, wooden rollers and a heavy wooden sledge on the ground, stacks of rough laterite and sandstone blocks waiting, small holes drilled in the blocks for lifting pegs.',
   'Construction scenes on the Bayon inner gallery; the lifting holes are visible on Angkor stones (HISTORICALLY_SUPPORTED).'),
 B('bld-rest-house', 'Rest house with fire (dharmasala)', 'ធម្មសាលា', '14 × 5 m', '10k',
   'A rest house of King Jayavarman VII on a royal road (c. 1200): a long narrow building of red laterite blocks with sandstone door frames, thick walls with small balustered windows, a stone-vaulted roof, a squat stepped tower over the east end, a doorway at the west with a small fire burning on a stone hearth.',
   'The "houses with fire" on the royal roads are listed in the Preah Khan stele (121 houses) and several survive (HISTORICALLY_CONFIRMED).'),
 B('bld-hospital', 'Hospital chapel (arogyasala)', 'អារោគ្យសាលា', '15 × 12 m', '10k',
   'A hospital chapel of Jayavarman VII: a small laterite enclosure wall with a gate, a single sandstone tower shrine with a doorway facing east, a small library building of laterite, a square pond with laterite steps beside it.',
   '102 hospitals are recorded; their stone chapels survive (e.g. Ta Prohm Kel). The wards were wooden and are lost.'),
 B('bld-kitchen-garden', 'Kitchen garden plot', 'សួនបន្លែ', '4 × 3 m', '4k',
   'A small Khmer house garden: raised soil beds edged with bamboo, banana plants, lemongrass clumps, chilli bushes, a small woven bamboo fence, a clay water jar.'),
]

FIELD = [
 B('field-paddy-bund', 'Rice paddy plot with bunds', 'ស្រែ', '8 × 6 m', '4k',
   'A small flooded Cambodian rice paddy seen from above at an angle: low earth bunds (dikes) round a level plot of shallow muddy water, a gap in one bund to let water through, flat and empty, no plants.'),
 B('plant-rice-seedbed', 'Rice seedling bed', 'ថ្នាលសំណាប', '1 × 1 m patch', '2k', 'A dense patch of bright light-green rice seedlings 15 cm tall growing thickly in wet mud.'),
 B('plant-rice-transplanted', 'Transplanted rice clump', 'ស្ទូងស្រូវ', '0.3 m', '1k', 'One clump of young rice plants just transplanted: about eight thin green shoots 25 cm tall, slightly tilted, roots in a little mud.'),
 B('plant-rice-growing', 'Growing rice clump', 'ស្រូវខៀវ', '0.8 m', '1k', 'One clump of growing rice: dense deep-green leaves about 80 cm tall, arching gracefully.'),
 B('plant-rice-ripe', 'Ripe rice clump', 'ស្រូវទុំ', '1.0 m', '2k', 'One clump of ripe rice: golden-yellow stalks about 1 m tall, heavy drooping panicles of grain bending the stems.'),
 B('plant-rice-stubble', 'Rice stubble', 'គល់ចំបើង', '0.2 m', '1k', 'One clump of rice stubble after harvest: short pale-yellow cut stems 15–20 cm tall in dry cracked mud.'),
 B('prop-rice-sheaf', 'Rice sheaf', 'កណ្ដាប់ស្រូវ', '0.9 m', '1k', 'A sheaf of harvested golden rice stalks with heavy grain heads, tied in the middle with a twist of straw.'),
]

ROADS = [
 B('road-causeway', 'Royal road segment (laterite causeway)', 'ផ្លូវរាជ្យ', '10 m long, 8 m wide', '2k',
   'A straight segment of an Angkorian royal road: a raised earth causeway about 1 m high with sloping sides, a surface of packed red laterite gravel with a paler worn middle and darker shoulders, short grass on the slopes.',
   'The royal roads (Preah Khan stele, LiDAR surveys) were raised embankments (HISTORICALLY_CONFIRMED).'),
 B('road-naga-bridge', 'Corbelled bridge with naga balustrades', 'ស្ពាននាគ', '20 m long, 15 m wide', '16k',
   'An Angkorian bridge after Spean Praptos (Kampong Kdei, 12th century): built of red laterite blocks, a row of thick piers with narrow tall corbelled (stepped, pointed) openings between them for the water, a flat roadway on top, low stone balustrades along both sides shaped as long naga serpent bodies, each end rising into a fan-shaped multi-headed naga hood.',
   'Spean Praptos, 87 m long with 21 arches, still carries traffic (HISTORICALLY_CONFIRMED).'),
 B('water-baray-edge', 'Baray embankment segment', 'ខ្នងបារាយណ៍', '10 m long', '2k', 'A segment of the embankment of an Angkorian baray (reservoir): a wide earth dyke with a laterite-stepped inner edge going down into still water, grass on top.'),
 B('water-canal-segment', 'Canal segment', 'ព្រែក', '10 m long, 4 m wide', '2k', 'A straight earth canal with sloping banks of reddish soil, low water, a few reeds at the edges.'),
 B('water-well', 'Village well / pond steps', 'អណ្ដូង', '2 m', '2k', 'A small Khmer village pond with laterite block steps down to the water and a large brown clay water jar on the top step.'),
]

VEHICLES = [
 B('vehicle-ox-cart', 'Ox cart (army supply)', 'រទេះគោ', '4 m long incl. shafts, 2.2 m high', '8k',
   'A Khmer ox cart of the Bayon reliefs: a wooden body on two large wooden wheels with many thin spokes, a long curved draught pole, an arched hood of woven bamboo and palm-leaf matting over the load bed, the cart empty, no animals.',
   'Bayon: supply carts with arched hoods follow the army (HISTORICALLY_CONFIRMED).'),
 B('vehicle-palanquin', 'Royal palanquin', 'វលភី', '3 m long', '8k',
   'A Khmer royal palanquin of the 12th century: a gilded wooden seat with a high carved back and armrests shaped like naga, carried on two long gilded poles that curve up at the ends into naga heads, red silk cushions, no bearers.',
   'Palanquins carry princesses and nobles in the Angkor Wat procession; Zhou Daguan describes gilded poles (HISTORICALLY_CONFIRMED).'),
 B('vehicle-rahat', 'Rahat water wheel (pedal pump)', 'រហាត់ទឹក', '3 m long, 1.6 m high', '6k',
   'A Cambodian treadle water wheel (rahat): a long wooden trough sloping from the water up to the field, a chain of small wooden paddles running inside it round two wooden sprockets, the upper sprocket on an axle with wooden pedal spokes, a bamboo frame and handrail for the person treading.',
   'HISTORICALLY_UNCERTAIN: the rahat is known from later Cambodian practice; its use at Angkor is an assumption.'),
 B('ship-chinese-junk', 'Chinese ocean junk (Song dynasty)', 'សំពៅចិន', '25 m long', '16k',
   'A Song-dynasty Chinese sea-going junk of the 12th–13th century: a broad flat-bottomed wooden hull with a blunt bow and a high square transom stern, a large stern rudder, a deck house aft with a small curved roof, two masts with brown woven-matting sails stiffened by horizontal bamboo battens, painted eyes on the bow, ropes and an anchor of wood and stone.',
   'After the Quanzhou wreck (13th c.) and Song paintings; a junk is carved on the Bayon (HISTORICALLY_CONFIRMED).'),
 B('ship-war-canoe', 'Khmer war canoe', 'ទូកចម្បាំង', '18 m long', '10k',
   'A Khmer war canoe of the Bayon naval battle (1177–81): a long narrow wooden hull with the prow and stern rising into carved naga or garuda heads, rows of paddlers\' seats, a small raised platform at the stern for the commander with a parasol socket, painted in red and black.',
   'Bayon and Banteay Chhmar naval scenes on the Tonle Sap (HISTORICALLY_CONFIRMED).'),
 B('ship-dugout-canoe', 'Fishing dugout canoe', 'ទូកអ៊ុំ', '6 m long', '4k', 'A small Cambodian fishing canoe dug out from a single log, narrow with pointed ends, a woven fish basket and a paddle inside.'),
 B('ship-bamboo-raft', 'Bamboo raft', 'ក្បូនឫស្សី', '6 × 2.5 m', '4k', 'A river raft of thick bamboo poles lashed side by side with rattan, a second layer of cross poles, a small thatched shelter in the middle, a long punting pole lying on it.'),
]
