/**
 * The iPhone build (D73): the phone page as an installable web app ("Add to Home Screen"
 * in Safari) that runs offline. Apple only builds native apps on a Mac, so the iPhone gets
 * the same page the Android app wraps, plus a web manifest and this service worker.
 *
 * Pure helpers (unit-tested); the build (vite.mobile.config.ts) writes sw.js with them and
 * mobile.ts registers it.
 */

/** Files the service worker keeps for offline play: everything built except itself and maps. */
export function offlineFiles(files: readonly string[]): string[] {
  const keep = files
    .map((f) => f.replace(/\\/g, '/').replace(/^\.?\//, ''))
    .filter((f) => f && f !== 'sw.js' && !f.endsWith('.map') && !f.startsWith('.'));
  return ['./', ...[...new Set(keep)].sort().map((f) => `./${f}`)];
}

/** A short, stable version from the file list (and their sizes): a new build = a new cache. */
export function cacheVersion(entries: readonly (readonly [string, number])[]): string {
  let h = 2166136261;
  for (const [name, size] of [...entries].sort((a, b) => a[0].localeCompare(b[0]))) {
    for (const ch of `${name}:${size};`) {
      h ^= ch.charCodeAt(0);
      h = Math.imul(h, 16777619) >>> 0;
    }
  }
  return h.toString(36);
}

/** The service worker: cache-first for the game's own files, old caches dropped on update. */
export function serviceWorkerSource(files: readonly string[], version: string): string {
  return `// Khmer Kingdoms offline cache (generated by vite.mobile.config.ts, D73).
const CACHE = 'khmer-kingdoms-${version}';
const FILES = ${JSON.stringify(files)};
self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(FILES)).then(() => self.skipWaiting()));
});
self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('khmer-kingdoms-') && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});
self.addEventListener('fetch', (e) => {
  if (e.request.method !== 'GET' || new URL(e.request.url).origin !== location.origin) return;
  e.respondWith(
    caches.match(e.request, { ignoreSearch: true }).then((hit) => hit || fetch(e.request)),
  );
});
`;
}

export interface OfflineHost {
  isSecureContext: boolean;
  location: { protocol: string };
  navigator: { serviceWorker?: unknown };
  Capacitor?: unknown;
}

/**
 * Register the offline cache only as a web app: not inside the Android app (Capacitor already
 * ships the files), not on file://, and only where service workers exist (https or localhost).
 */
export function shouldRegisterOffline(w: OfflineHost): boolean {
  if (w.Capacitor) return false;
  if (!w.isSecureContext || !w.navigator.serviceWorker) return false;
  return w.location.protocol === 'https:' || w.location.protocol === 'http:';
}

/** Phones held upright: the kingdom is landscape only, so we ask to turn the phone. */
export function isPortrait(width: number, height: number): boolean {
  return height > width * 1.05;
}

/** iPhone / iPad Safari, which has no install prompt: we show how to add it to the Home Screen. */
export function isIos(userAgent: string, maxTouchPoints: number, platform: string): boolean {
  if (/iPhone|iPad|iPod/i.test(userAgent)) return true;
  // iPadOS 13+ reports itself as a Mac with a touch screen.
  return platform === 'MacIntel' && maxTouchPoints > 1;
}
